# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea6d134771ca3c93a5e81a039181e5c6d5cc1488b09c1e65fc83745fb836160b5c1e090a87090e5a3affc425030a2bb0f684e1ac8ea5fb662b7a417b034df33b

test:
  secret_key_base: 1f65dc25fcd11fd7bd574eb1a5b3ba646e0aa8cf60467719976efa9c23c8089b73f9f42ce8bcd6122ab1519b61af4eb3e4c38ce47bbd53861d73a46ce025536e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
